### PR TITLE
Updating AlgoScreen from class component to functional component

### PR DESCRIPTION
**Pull request by bavichugo**
## Description
- I was bored in a Saturday night and for some reason I ended up in csvistools repo. I saw that a lot of it was old code and decided to improve it.

## Changes
- Updated `AlgoScreen` component from class component to functional component
- Created a component for the 404 screen
- Removed some unused variables and states
- Destructured `algoMap` to make the code more readable

## Note
1. I did not test all of the functionalities of all different data structures.
3. Someone seems to have added a Vercel bot by mistake that fails PRs.

### CODE REVIEW

**Comment by luciankt** [comment]
Looks good. Only issue I found is that the pseudocode no longer switches correctly when pressing the button in the top right. I think this is because these two lines which change the visibility of the pseudocode layers were removed.

image

**Comment by luciankt** [comment]
Also if you have any idea how to remove Vercel feel free to - but if it requires admin permissions on the repo then unfortunately I don't think any active contributors can do that.

**Comment by bavichugo** [comment]
> Looks good. Only issue I found is that the pseudocode no longer switches correctly when pressing the button in the top right. I think this is because these two lines which change the visibility of the pseudocode layers were removed.
> 
> image

I fixed the mistake. Good catch.

**Comment by luciankt** [comment]
Perfect. Works now!

**Pull request merged**
