### PR TITLE
add build tree functionality

### PR DESCRIPTION
**Pull request by jacksherling**

### CODE REVIEW

**Comment by luciankt** [comment]
image
The text box is a little bit large at least for my laptop screen. Maybe it could adjust automatically to the screen size, or if you don't want to deal with css just make it a little smaller. Chances are people won't be building trees that large. Ideally we can make it so the text box lets you scroll horizontally if users type more than can fit, but not sure how hard that is. Feel free to look into it if you want.

Error text saying what went wrong would be great when the button doesn't let you build the tree. The implementation for error text is a little bit convoluted, but take a look at how we did this in BuildHeap for non-numeric inputs (or on most other pages) if you'd like to try. 

I tried the invalid input `1,8,10|0|2|4|9` and the page threw uncaught errors & didn't respond. I think the issue is related to child nodes being out of order compared to the parent, but for other cases it did seem to catch it like `1,8|0|9|11`.

I also tried `1,8,10|0||9|11` and the same happened. I guess it doesn't like having an empty child node.

Great work so far! This is already super useful for visualizing 2-4 trees. 😎🔥

**Comment by luciankt** [comment]
Looks great! The display is still a little weird for these other options sections on smaller screens but to be fair it's pretty much impossible to make everything look great on all screen sizes 🤷 I'll see if I can fix it when I mess with other css/display things unless you want to keep trying. Great work 😊  
image

**Comment by ljones315** [comment]
This is looking really good 👀 . I noticed though that the order property within a node isn't being explicitly checked, only the order between parent/children data, so weird things like this are allowed:

Screenshot 2023-11-02 at 11 31 06 AM

I also noticed that sometimes the error message doesn't perfectly match the issue (though I can't see immediately why). Like here the input was `10,30|0|20|11,32`, so the issue is that 11 < 30, but I got the following error:

Screenshot 2023-11-02 at 11 34 16 AM

**Comment by jacksherling** [comment]
Thanks for the feedback! Fixed the point about order being respected within nodes. For the point about the incorrect error message, it can't really be fixed without moving a lot of logic around. Basically, the algorithm is adding 11,32 to be in between 10 and 30, because it uses the first value 11 to recurse. The error check later confirms the tree shape being wrong because it was initially added to the wrong place because of the bad order.

Maybe we can add an issue to make the error message better for later? But right now it's technically right given my current algorithm for building the tree.

**Comment by ljones315** [comment]
Looks amazing!!

I think it's good to go! I'll let @luciankt take one last look at it too, and then we can merge 🤠 

(also I added details in the commit messages for the small changes I just made)

**Comment by luciankt** [comment]
Everything looks good to me! I haven't encountered any other problems besides the not-super-clear error messages in some cases, but that's minor enough to not worry about for now imo.

If you guys are all done with changes then feel free to merge Liam! 🚀

**Pull request merged**
