### PR TITLE
Kth Select Font Fix

### LINKED ISSUE #231: Kth select superscript formatting
The superscript lowercase T in the header of this [window](https://csvistool.com/QuickSelect) kinda look funky in Safari 😳

Screenshot 2023-04-07 at 4 04 21 PM

### PR DESCRIPTION
**Pull request by ShmulTomer**
the "th" superscript appeared uneven, changed it to subscript, looks better

closes #231

### CODE REVIEW

**Comment by ljones315** [comment]
I'm cool with this but I'll let the design master @skapoor68 give his opinion on the superscript vs subscript

**Comment by iWatger** [comment]
I think the subscript would get a little confusing imo. Usually the ordinal number part is superscript

**Comment by ShmulTomer** [comment]
image
Latest commit fixes the superscript on the algorithm's page

On the home screen though it will still look like this 
image
I played around a while with it, to fix it here we would need to redo the buttons from using <input> to another element, such as React <button>, which I don't think is worth for this small issue

the reason is that <input> only takes plain text, and the current superscript letters are inherently different sizes; the way I fixed on the algorithm page is to use the <sup> HTML tag, but you can't use that within an <input> tag value

**Comment by skapoor68** [comment]
Yes I think the most recent push by Tomer is the best resolution for this. I also agree it'd be a lot of work to switch the <input> tag to a <button> tag. But that's something that can be looked into in the future.

**Pull request merged**
