### PR TITLE
Random Data Entry for Lists 

### PR DESCRIPTION
**Pull request by ShmulTomer**
Added for 4 lists (ArrayList, SLL, DLL, CSLL)

If others are good with the functionality, I'll do the rest of the algorithms/data structures

addresses issue #256

### CODE REVIEW

**Comment by skapoor68** [comment]
Yeah these look good. Feel free to add to the remaining visualizations.

**Comment by ShmulTomer** [comment]
Ok random is done for everything 

only thing im not certain about is where to put the random button for the 2 HashMaps, but besides that everything should be functional

closes #257

**Comment by skapoor68** [comment]
These look good. I'll try doing something to better format the HashMap toolbar. Then it should be good to merge

**Comment by skapoor68** [comment]
I pushed a commit for HashMaps. Everything looks good from a visual perspective. The only issue is that in open addressing, you can't enter characters when you have the Hash Strings or True Hash Function enabled. But it works in closed addressing. I'm not sure why this is and if this was something I did or was there from prior changes.

**Comment by skapoor68** [comment]
> I pushed a commit for HashMaps. Everything looks good from a visual perspective. The only issue is that in open addressing, you can't enter characters when you have the Hash Strings or True Hash Function enabled. But it works in closed addressing. I'm not sure why this is and if this was something I did or was there from prior changes.

Should be resolved now. Let me know if everything looks good before merging

**Comment by ShmulTomer** [comment]
Looks good to me, I like how you reorganized for HashMap

**Pull request merged**
